### ISSUE TITLE
Multiple timers don't work on same page?

### ISSUE THREAD

**Issue by moshahmed** [walmik/timer.jquery#47] opened 2015-11-29 12:02 UTC
$('#clockdiv').timer({ format: '%h:%m:%s' });
  $('#clockdiv2').timer({ format: '%h:%m:%s' });

**Comment by walmik** [comment] 2015-11-30 21:35
This is a dupe of https://github.com/walmik/timer.jquery/issues/27
Lets continue to track it from there.

**Closed by walmik** 2015-11-30 21:35 UTC
